permission-based-help-command: true # If this is set to true than the player will only see commands they have permission to use
raid-cooldown: 60 # Amount of time in minutes before a team can be raided again
squid-spawn-enabled: false # If squid spawners will spawn any squids
team-chat-format: "&7[&e{rank}&7] &5{name} &c> {message}" # Format for team chat : {rank} {name} {message}
team-chunk-limit: 20 # Maximum amount of chunks a team can claim
team-name-character-limit: 16 # Maximum amount of characters a team name can have

chat:
  no-team: "&r&cNone&r" # When {team} is in your Chat Formatter and the player has no team this is the name that will be given. EX : Changes color to indicate they do not have a team
  team-format: "&7[&e{rank}&7] &5{name} &c> {message}" # Format for team chat : {rank} {name} {message}

pagination: # This is the maximum number of items that will be displayed per page
  claims: 20
  help: 5
  top: 10

points: # Minimum amount and maximum amount of points a team can have
  minimum: 0
  maximum: 100000

timer: # A countdown timer for each command
  invite: 60
  join: 60
  raid: 20

walk-into-area: # The message the player will see when walking into a different chunk owner. Leave blank ("") to send no message
  claimed-to-claimed: "{prefix} &4You are now walking in &5{to}'s &4territory." # {prefix} {from} {to}
  claimed-to-none: "{prefix} &aYou are now walking in the wild." # {prefix} {from}
  none-to-claimed: "{prefix} &4You are now walking in &5{to}'s &4territory." # {prefix} {to}